# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codepath@ucsb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for codepath@ucsb
  pod 'Alamofire'
  target 'codepath@ucsbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'codepath@ucsbUITests' do
    # Pods for testing
  end

end
